---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litmus-preview
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/litmuschaos/litmus-cd'
    path: k8s-infra/litmus-preview
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: litmus-preview
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
