---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-hub-litmuschaos-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/litmuschaos/litmus-cd'
    path: k8s-infra/prod-hub-litmuschaos
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-hub-litmuschaos
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true